### ISSUE TITLE
how to reload with reloadium not change my app when i save again file

### ISSUE THREAD

**Issue by bobwatcherx** [buganini/PUI#1]
code 
```
# example/hello_world.py
import reloadium

from PUI.PySide6 import *

class Example(Application):
    def content(self):
        with Window(title="test", size=(320,240)):
            Label("efefe 22dwdw")


def after_reload(actions):
    PUIView.reload()

if __name__ == "__main__":
    reloadium: after_reload
    root = Example()
    root.run()

```

command
root@mopt-HP-Convertible-x360-11-ab1XX:/home/mopt/belajar/qpuipro# reloadium run main.py 
■■■■■■■■■■■■■■■
Reloadium 1.1.0
■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a star at https://github.com/reloadware/reloadium
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

Loaded 1 watched modules so far from paths:
 - /home/mopt/belajar/qpuipro/**/*.py

Update Module: __main__
Update Method: Example.content(7-9)

Update Module: __main__
Update Method: Example.content(7-9)

**Comment by buganini** [comment]
Hi, you need to keep the comment for reloadium like this
```
# reloadium: after_reload
def after_reload(actions):
    PUIView.reload()
```

Reference:
https://reloadium.io/documentation/decorators

**Comment by bobwatcherx** [comment]
> Hi, you need to keep the comment for reloadium like this
> 
> ```
> # reloadium: after_reload
> def after_reload(actions):
>     PUIView.reload()
> ```
> 
> Reference: https://reloadium.io/documentation/decorators

and button click i have error like this

my code 



from PUI.PySide6 import *

data = State()
data.var = 0

class QtExample(QtApplication):
    def content(self):
        with QtWindow(title="blah"):
            with QtVBox():
                with QtHBox():
                    QtButton("-", self.on_minus)
                    QtLabel(f"{data.var}")
                    QtButton("+", self.on_plus)

                QtLineEdit(data("var")) # binding

    def on_minus(self):
        data.var -= 1

    def on_plus(self):
        data.var += 1

root = QtExample()
root.run()


error
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/puifr# python3 main.py 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
## <ERROR OF content() > QtExample 139785489202288
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PUI/view.py", line 75, in update
    self.content() # V-DOM builder
  File "/home/miop/belajar/puifr/main.py", line 12, in content
    QtButton("-", self.on_minus)
TypeError: QtButton.__init__() takes 2 positional arguments but 3 were given
## </ERROR OF content()>

**Comment by buganini** [comment]
Sorry, the button interface is changed in v0.2.0
it's now 
QtButton("-").click(self.on_minus)

**Comment by buganini** [comment]
does it work?

**Comment by bobwatcherx** [comment]
Yes . I'm just waiting to use the properties flet on Pui
